version: '3.1'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root1234PWD"
      MYSQL_USER: XoxUser
      MYSQL_PASSWORD: "1234PWD"
      MYSQL_DATABASE: fundamental_db
    ports:
      - "3306:3306"
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:

# docker-compose up -d