version: '3.1'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: XoxUser
      MYSQL_PASSWORD: "#1234PWD"
      MYSQL_DATABASE: fundamental_db  # Optional: Create a specific database
    ports:
      - "3306:3306"  # Map host port 3307 to container port 3306
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - dbdata2:/var/lib/mysql
volumes:
  dbdata2:
